# FLUENDO S.A.
# Copyright (C) <2024>  <support@fluendo.com>
# GUW configuration file for fluendo-cerbero project: to use the upstream.
# 

[[remotes]]
name = "fluendo"
url = "git@github.com:fluendo/cerbero.git"

[[remotes]]
name = "origin"
url = "https://github.com/GStreamer/cerbero.git"

[target]
remote = "fluendo"
branch = "COM-10606-sync-cerbero"

[source]
remote = "origin"
branch = "main"

[[features]]
remote = "fluendo"
name = "COM-10816-strip-and-section-mixins"
summary = "Make sync method in Strip class public"
pr = "https://gitlab.freedesktop.org/gstreamer/cerbero/-/merge_requests/1521"
status = "integrated"

[[features]]
remote = "fluendo"
name = "COM-10670-recipe-warn-override"
summary = "cookbook: Warn about recipe override by name"
pr = "https://gitlab.freedesktop.org/gstreamer/cerbero/-/merge_requests/1497"
status = "integrated"

[[features]]
remote = "fluendo"
name = "COM-10979-show-config-build-tools"
summary = "Adding more options for show-config (build tools config and universal archs)"
pr = "https://gitlab.freedesktop.org/gstreamer/cerbero/-/merge_requests/1538"
status = "integrated"

[[features]]
remote = "fluendo"
name = "COM-10967-fix-wix-annotations-for-old-python"
summary = "import annotations is missing in cerbero/packages/windows/wix_on_ninja.py"
pr = "https://gitlab.freedesktop.org/gstreamer/cerbero/-/merge_requests/1536"
status = "integrated"

[[features]]
remote = "fluendo"
name = "COM-12259-fix-variants-override"
summary = "Cerbero configs: Fixing variants without changing the order of loading"
pr = "https://gitlab.freedesktop.org/gstreamer/cerbero/-/merge_requests/1550"
status = "merging"
